package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "argparser",
    srcs = [],
    hdrs = ["argparser.h"],
    deps = [],
)

cc_library(
    name = "util",
    srcs = [],
    hdrs = ["util.h"],
    deps = [
        "@opencv3//:common",
    ],
)

cc_library(
    name = "renderer",
    srcs = [],
    hdrs = ["renderer.h"],
    deps = [
        "@opencv3//:common",
    ],
)
