package(
    default_visibility = ["//visibility:public"],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "//computer-vision/assignments/common:util",
        "@opencv3//:common",
    ],
)
