package(
    default_visibility = ["//visibility:public"],
)

cc_binary(
    name = "assignment4",
    srcs = ["main.cc"],
    deps = [
        "//computer-vision/assignments/assignment4/bird_view",
        "//computer-vision/assignments/assignment4/camera_calibration:calibrator",
        "//computer-vision/assignments/assignment4/hw4_argparser:HW4Argparser",
    ],
)
