package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "bird_view",
    srcs = ["view_processor.cc"],
    hdrs = ["view_processor.h"],
    deps = [
        "//computer-vision/assignments/common:util",
        "@opencv3//:common",
    ],
)
