package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "HW4Argparser",
    srcs = [],
    hdrs = ["HW4Argparser.h"],
    deps = ["//computer-vision/assignments/common:argparser"],
)
