package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "calibrator",
    srcs = ["camera_calibrator.cc"],
    hdrs = ["camera_calibrator.h"],
    deps = [
        "//computer-vision/assignments/common:util",
        "@opencv3//:common",
    ],
)
